stages:
  - build

build:
  stage: build
  tags:
    - docker
  image: centos:7
  variables:
    BUNDLE_VERSION: "1.10.3-32-g63e5bb2"
  before_script:
    - echo "Using tarantool-enterprise-bundle ${BUNDLE_VERSION}"
    - curl -O -L https://tarantool:${DOWNLOAD_TOKEN}@download.tarantool.io/enterprise/tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - tar -xzf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - rm -rf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - export PATH=$PWD/tarantool-enterprise:$PATH
    - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - yum -y install git gcc make cmake unzip python36u-pip
    - tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
    - export PATH=.rocks/bin:$PATH
    - pip3.6 install -r test/requirements.txt
  script:
    - tarantoolctl rocks make BUILD_DOC=YES
    - pytest -v
